# Stage 1: Install dependencies and build the application
FROM node:21 AS backend-builder

WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY ./package.json ./package-lock.json /app/

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . /app

# Build the application (optional if you need to build assets)
# RUN npm run build

# Stage 2: Create a lightweight image for production
FROM node:21-slim

WORKDIR /app

# Copy only the necessary files from the first stage
COPY --from=backend-builder /app /app

# Expose the port the app runs on (optional, replace 3000 with your app's port)
EXPOSE 3000

# Command to run the application
CMD ["npm", "start"]






# FROM node:alpine 

# WORKDIR /app  

# COPY ./package.json /app

# RUN npm install 

# COPY   . /app

# CMD [ "npm" , "start" ] 
