version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.29.78:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

    
#   mongodb:
#     image: mongo
#     volumes:
#       - data:/data/db
#     networks:
#       - backend_network

#   backend:
#     build: ./backend
#     container_name: backend-container
#     ports:
#       - "9000:9000"
#     volumes:
#       - ./backend:/app
#     working_dir: /app
#     command: ["npm", "run", "dev"]
#     environment:
#       - NODE_ENV=development
#     depends_on:
#       - kafka
#       - redis
#       - mongodb
#     networks:
#       - backend_network

#   frontend:
#     build: ./frontend
#     ports:
#       - "3000:3000"
#     volumes:
#       - ./frontend/src:/app/src
#     stdin_open: true
#     tty: true
#     networks:
#       - frontend_network
#       - backend_network

# # Volumes
# volumes:
#   data:

# # Networks
# networks:
#   backend_network:
#   frontend_network:





