version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
  backend:
    build: ./backend
    container_name: basic-container
    ports:
      - 9000:9000
    volumes:
      - ./backend:/index

  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db

  prom-server:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./backend/prometheus-config.yml:/etc/prometheus/prometheus.yml

volumes:
  data: