✅ Summary of Flow:
✅ OTP generated by GenOtp().

✅ OTP saved in otpStore[email] = { otp, expiresAt }.

✅ OTP sent via email.

✅ During login, OTP checked from otpStore.

✅ On success, token generated and OTP cleared.

